### ISSUE TITLE
Error on "docker compose up -d --build"

### ISSUE THREAD

**Issue by amirmm11** [ampl/amplpyfinance#1]
Getting this error after running the  `docker compose up -d --build`

`=> ERROR [amplopt/testing:amplpyfinance-celery-v1 3/9] RUN cd /opt/ && curl -O https://ampl.com/dl/modules/ampl-module.linux64.tgz &&     tar xzvf ampl-module.linux64.tgz && rm ampl-module.linu`

**Comment by fdabrandao** [comment]
Hi @amirmm11,

Thanks for reporting this issue! If has been fixed in https://github.com/ampl/amplpyfinance/commit/78c1fb97f7987a7f3a6b0f8461cd3766ad4513c7.

**Comment by fdabrandao** [comment]
The docker configuration has just been updated to use [amplpy.modules](https://dev.ampl.com/ampl/python/modules.html).

The installation steps used in the new [the updated Dockerfile](https://github.com/ampl/amplpyfinance/blob/master/deployment/docker/queue/Dockerfile) are now just:

```
RUN python -m pip install amplpy --no-cache-dir # Install amplpy
RUN python -m amplpy.modules install highs coin gurobi --no-cache-dir # Install modules
```
